(in-package #:cl-tty-kit/test)

(defun test-ansi ()
  (is (string= (ansi-clear-screen) (format nil "~C[2J" #\Esc)))
  (is (string= (ansi-clear-line) (format nil "~C[2K" #\Esc)))
  (is (string= (ansi-move-cursor 3 4) (format nil "~C[3;4H" #\Esc)))
  (is (string= (ansi-hide-cursor) (format nil "~C[?25l" #\Esc)))
  (is (string= (ansi-show-cursor) (format nil "~C[?25h" #\Esc)))
  (is (string= (ansi-enter-alternate-screen) (format nil "~C[?1049h" #\Esc)))
  (is (string= (ansi-exit-alternate-screen) (format nil "~C[?1049l" #\Esc)))
  (is (string= (ansi-enable-bracketed-paste) (format nil "~C[?2004h" #\Esc)))
  (is (string= (ansi-disable-bracketed-paste) (format nil "~C[?2004l" #\Esc)))
  (is (string= (ansi-enable-focus-reporting) (format nil "~C[?1004h" #\Esc)))
  (is (string= (ansi-disable-focus-reporting) (format nil "~C[?1004l" #\Esc)))
  (is (string= (ansi-request-cursor-position) (format nil "~C[6n" #\Esc)))
  (is (string= (ansi-request-device-attributes) (format nil "~C[c" #\Esc)))
  (is (string= (ansi-hyperlink "http://x" "link")
               (format nil "~C]8;;http://x~C\\link~C]8;;~C\\"
                       #\Esc #\Esc #\Esc #\Esc)))
  (is (string= (ansi-hyperlink
                (format nil "http://x~C]0;pwn~C" #\Esc (code-char 7))
                (format nil "safe~C[31m" #\Esc))
               (format nil "~C]8;;http://x]0;pwn~C\\safe[31m~C]8;;~C\\"
                       #\Esc #\Esc #\Esc #\Esc)))
  (is (string= (ansi-bell) (string (code-char 7))))
  (is (string= (ansi-bell 3) (make-string 3 :initial-element (code-char 7))))
  (signals (error c) (ansi-bell -1) (is c))
  (signals (error c) (ansi-bell 1.5) (is c))
  (is (string= (ansi-reset-terminal) (format nil "~Cc" #\Esc)))
  (is (string= (ansi-begin-synchronized-update) (format nil "~C[?2026h" #\Esc)))
  (is (string= (ansi-end-synchronized-update) (format nil "~C[?2026l" #\Esc)))
  (is (string= (ansi-default-foreground) (format nil "~C[39m" #\Esc)))
  (is (string= (ansi-default-background) (format nil "~C[49m" #\Esc)))
  (is (string= (ansi-set-clipboard "hi")
               (format nil "~C]52;c;aGk=~C\\" #\Esc #\Esc)))
  (is (string= (ansi-set-clipboard "hi" :target "p")
               (format nil "~C]52;p;aGk=~C\\" #\Esc #\Esc)))
  (signals (error c) (ansi-set-clipboard "hi" :target "c;BAD") (is c))
  (signals (error c) (ansi-set-clipboard "hi" :target "") (is c))
    (is (string= (ansi-set-palette-color 1 255 0 0)
                 (format nil "~C]4;1;rgb:FF/00/00~C\\" #\Esc #\Esc)))
    (is (string= (ansi-reset-palette) (format nil "~C]104~C\\" #\Esc #\Esc)))
    (is (string= (ansi-reset-palette 3) (format nil "~C]104;3~C\\" #\Esc #\Esc)))
    (signals (error c) (ansi-set-palette-color -1 0 0 0) (is c))
    (signals (error c) (ansi-set-palette-color 0 256 0 0) (is c))
    (signals (error c) (ansi-reset-palette 256) (is c))
  (is (string= (ansi-request-foreground-color)
               (format nil "~C]10;?~C\\" #\Esc #\Esc)))
  (is (string= (ansi-request-background-color)
               (format nil "~C]11;?~C\\" #\Esc #\Esc)))
  (is (string= (ansi-enable-line-wrap) (format nil "~C[?7h" #\Esc)))
  (is (string= (ansi-disable-line-wrap) (format nil "~C[?7l" #\Esc)))
  (is (string= (ansi-cursor-next-line) (format nil "~C[1E" #\Esc)))
  (is (string= (ansi-cursor-next-line 3) (format nil "~C[3E" #\Esc)))
  (is (string= (ansi-cursor-previous-line 2) (format nil "~C[2F" #\Esc)))
  (is (string= (ansi-set-keyboard-enhancements 5)
               (format nil "~C[=5;1u" #\Esc)))
  (is (string= (ansi-set-keyboard-enhancements 5 3)
               (format nil "~C[=5;3u" #\Esc)))
  (signals (error c) (ansi-set-keyboard-enhancements -1) (is c))
  (is (string= (ansi-push-keyboard-enhancements 5)
               (format nil "~C[>5u" #\Esc)))
  (is (string= (ansi-pop-keyboard-enhancements)
               (format nil "~C[<1u" #\Esc)))
  (is (string= (ansi-pop-keyboard-enhancements 2)
               (format nil "~C[<2u" #\Esc)))
  (is (string= (ansi-bold) (format nil "~C[1m" #\Esc)))
  (is (string= (ansi-dim) (format nil "~C[2m" #\Esc)))
  (is (string= (ansi-italic) (format nil "~C[3m" #\Esc)))
  (is (string= (ansi-underline) (format nil "~C[4m" #\Esc)))
  (is (string= (ansi-blink) (format nil "~C[5m" #\Esc)))
  (is (string= (ansi-reverse) (format nil "~C[7m" #\Esc)))
  (is (string= (ansi-hidden) (format nil "~C[8m" #\Esc)))
  (is (string= (ansi-strikethrough) (format nil "~C[9m" #\Esc)))
  (is (string= (ansi-reset-style) (format nil "~C[0m" #\Esc)))
    (is (string= (ansi-sgr) (format nil "~C[m" #\Esc)))
    (is (string= (ansi-sgr 1 38 5 208)
                 (format nil "~C[1;38;5;208m" #\Esc)))
    (is (string= (ansi-sgr "4:3")
                 (format nil "~C[4:3m" #\Esc)))
    (signals (error c) (ansi-sgr -1) (is c))
    (signals (error c) (ansi-sgr (format nil "0m~C]52;c;pwn" #\Esc)) (is c))
    (signals (error c) (ansi-sgr "1;31") (is c))
  (is (string= (ansi-cursor-up) (format nil "~C[1A" #\Esc)))
  (is (string= (ansi-cursor-up 4) (format nil "~C[4A" #\Esc)))
  (signals (error c) (ansi-cursor-up -1) (is c))
  (is (string= (ansi-cursor-down 2) (format nil "~C[2B" #\Esc)))
  (is (string= (ansi-cursor-forward 3) (format nil "~C[3C" #\Esc)))
  (is (string= (ansi-cursor-back 5) (format nil "~C[5D" #\Esc)))
  (is (string= (ansi-cursor-column 12) (format nil "~C[12G" #\Esc)))
  (is (string= (ansi-cursor-row 7) (format nil "~C[7d" #\Esc)))
  (is (string= (ansi-insert-line) (format nil "~C[1L" #\Esc)))
  (is (string= (ansi-insert-line 2) (format nil "~C[2L" #\Esc)))
  (is (string= (ansi-delete-line 3) (format nil "~C[3M" #\Esc)))
  (is (string= (ansi-insert-char 4) (format nil "~C[4@" #\Esc)))
  (is (string= (ansi-delete-char) (format nil "~C[1P" #\Esc)))
  (is (string= (ansi-erase-char 5) (format nil "~C[5X" #\Esc)))
  (is (string= (ansi-repeat 3) (format nil "~C[3b" #\Esc)))
  (is (string= (ansi-save-cursor) (format nil "~C7" #\Esc)))
  (is (string= (ansi-restore-cursor) (format nil "~C8" #\Esc)))
  (is (string= (ansi-scroll-up 2) (format nil "~C[2S" #\Esc)))
  (is (string= (ansi-scroll-down) (format nil "~C[1T" #\Esc)))
  (is (string= (ansi-set-scroll-region 2 10)
               (format nil "~C[2;10r" #\Esc)))
  (is (string= (ansi-reset-scroll-region) (format nil "~C[r" #\Esc)))
  (is (string= (ansi-set-mode 25) (format nil "~C[?25h" #\Esc)))
  (is (string= (ansi-reset-mode 25) (format nil "~C[?25l" #\Esc)))
  (is (string= (ansi-set-mode 4 :private nil) (format nil "~C[4h" #\Esc)))
  (is (string= (ansi-reset-mode 4 :private nil) (format nil "~C[4l" #\Esc)))
  (signals (error c) (ansi-set-mode -1) (is c))
  (signals (error c) (ansi-reset-mode 1.5) (is c))
  ;; The generic mode builder reproduces the specific private-mode wrappers.
  (is (string= (ansi-enable-bracketed-paste) (ansi-set-mode 2004)))
  (is (string= (ansi-disable-bracketed-paste) (ansi-reset-mode 2004)))
  (is (string= (ansi-hide-cursor) (ansi-reset-mode 25)))
  (is (string= (ansi-set-window-title "hi")
               (format nil "~C]0;hi~C" #\Esc (code-char 7))))
  (is (string= (ansi-set-window-title
                (format nil "safe~C]0;pwn~C" #\Esc (code-char 7)))
               (format nil "~C]0;safe]0;pwn~C" #\Esc (code-char 7))))
  (is (string= (ansi-set-cursor-style :steady-bar)
               (format nil "~C[6 q" #\Esc)))
  (is (string= (ansi-set-cursor-style :default)
               (format nil "~C[0 q" #\Esc)))
  (is (string= (ansi-enable-mouse)
               (format nil "~C[?1002h~C[?1006h" #\Esc #\Esc)))
  (is (string= (ansi-enable-mouse :any)
               (format nil "~C[?1003h~C[?1006h" #\Esc #\Esc)))
  (is (string= (ansi-disable-mouse)
               (format nil "~C[?1006l~C[?1002l" #\Esc #\Esc)))
  (signals (error c) (ansi-set-cursor-style :nope) (is c))
  (signals (error c) (ansi-enable-mouse :nope) (is c)))
