(in-package #:cl-tty-kit/test)

(defun test-ansi ()
  (is (string= (ansi-clear-screen) (format nil "~C[2J" #\Esc)))
  (is (string= (ansi-clear-line) (format nil "~C[2K" #\Esc)))
  (is (string= (ansi-move-cursor 3 4) (format nil "~C[3;4H" #\Esc)))
  (is (string= (ansi-hide-cursor) (format nil "~C[?25l" #\Esc)))
  (is (string= (ansi-show-cursor) (format nil "~C[?25h" #\Esc)))
  (is (string= (ansi-enter-alternate-screen) (format nil "~C[?1049h" #\Esc)))
  (is (string= (ansi-exit-alternate-screen) (format nil "~C[?1049l" #\Esc)))
  (is (string= (ansi-enable-bracketed-paste) (format nil "~C[?2004h" #\Esc)))
  (is (string= (ansi-disable-bracketed-paste) (format nil "~C[?2004l" #\Esc)))
  (is (string= (ansi-set-keyboard-enhancements 5)
               (format nil "~C[=5;1u" #\Esc)))
  (is (string= (ansi-set-keyboard-enhancements 5 3)
               (format nil "~C[=5;3u" #\Esc)))
  (is (string= (ansi-push-keyboard-enhancements 5)
               (format nil "~C[>5u" #\Esc)))
  (is (string= (ansi-pop-keyboard-enhancements)
               (format nil "~C[<1u" #\Esc)))
  (is (string= (ansi-pop-keyboard-enhancements 2)
               (format nil "~C[<2u" #\Esc)))
  (is (string= (ansi-bold) (format nil "~C[1m" #\Esc)))
  (is (string= (ansi-reset-style) (format nil "~C[0m" #\Esc))))
