(in-package #:cl-tty-kit/test)

(defparameter +basic-input-cases+
  `((#(97 98 99)
     ((:character ,#\a nil)
      (:character ,#\b nil)
      (:character ,#\c nil))
     "ASCII input should decode to character events.")
    (#(3)
     ((:special :control-c nil))
     "Control characters should map to special key events.")
    (#(97 227 129 130 98)
     ((:character ,#\a nil)
      (:character ,#\あ nil)
      (:character ,#\b nil))
     "Mixed ASCII and UTF-8 input should preserve event order.")
    (,(concatenate 'string (string #\Esc) "[200~")
     ((:special :paste-start nil))
     "Bracketed paste start should decode as a special event.")
    (,(concatenate 'string (string #\Esc) "[201~")
     ((:special :paste-end nil))
     "Bracketed paste end should decode as a special event.")
    (,(concatenate 'string (string #\Esc) "[u")
     ((:special :escape nil)
      (:character ,#\[ nil)
      (:character ,#\u nil))
     "An empty CSI-u body falls back to ordinary decoding instead of crashing.")))

(defparameter +streaming-input-cases+
  `(((,(string #\Esc) "[A")
     ((:special :up nil))
     "CSI sequences should survive chunk boundaries.")
    ((,(concatenate 'string (string #\Esc) "O") "P")
     ((:special :f1 nil))
     "SS3 sequences should survive chunk boundaries.")
    ((#(227 129) #(130 98))
     ((:character ,#\あ nil)
      (:character ,#\b nil))
     "Three-byte UTF-8 sequences should survive chunk boundaries.")
    ((#(194) #(162 33))
     ((:character ,#\¢ nil)
      (:character ,#\! nil))
     "Two-byte UTF-8 sequences should survive chunk boundaries.")
    ((#(240 159 152) #(128 33))
     ((:character ,#\😀 nil)
      (:character ,#\! nil))
     "Four-byte UTF-8 sequences should survive chunk boundaries.")
    ((,(concatenate 'string (string #\Esc) "[20")
      "0~he"
      ,(concatenate 'string "llo" (string #\Esc) "[201~"))
     ((:paste "hello" nil))
     "Bracketed paste should aggregate across chunk boundaries."
     :collect-bracketed-paste t)
    ((,(concatenate 'string (string #\Esc) "[200~")
      "hello"
      ,(concatenate 'string (string #\Esc) "[201~"))
     ((:paste "hello" nil))
     "Bracketed paste should aggregate whole payload chunks."
     :collect-bracketed-paste t)
    ((,(concatenate 'string
                    (string #\Esc)
                    "[200~abc"
                    (string #\Esc)
                    "[20")
      "1~")
     ((:paste "abc" nil))
     "Bracketed paste terminators should survive chunk boundaries."
     :collect-bracketed-paste t)
    ((,(concatenate 'string (string #\Esc) "[200~")
      #(227 129)
      #(130 98 27 91 50 48 49 126))
     ((:paste "あb" nil))
     "Bracketed paste should preserve UTF-8 payloads across chunks."
     :collect-bracketed-paste t)
    ((,(concatenate 'string
                    (string #\Esc)
                    "[200~hello"
                    (string #\Esc)
                    "[201~x"))
     ((:paste "hello" nil)
      (:character ,#\x nil))
     "Trailing events should remain after aggregated paste payloads."
     :collect-bracketed-paste t)
    ((,(concatenate 'string (string #\Esc) "[105;")
      "6u")
     ((:character ,#\i (:control :shift)))
     "CSI-u sequences should survive chunk boundaries.")
    ((,(concatenate 'string (string #\Esc) "[99999999")
      "u")
     ((:special :escape nil)
      (:character ,#\[ nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\9 nil)
      (:character ,#\u nil))
     "Overflowing CSI-u sequences should fall back to ordinary decoding.")))

(defparameter +streaming-equivalence-cases+
  `(("abc" nil)
    (#(194 162 33) nil)
    (#(97 227 129 130 98) nil)
    (#(240 159 152 128 33) nil)
    (,(concatenate 'string (string #\Esc) "[A") nil)
    (,(concatenate 'string (string #\Esc) "OP") nil)
    (,(concatenate 'string (string #\Esc) "[1;aC") nil)
    (,(concatenate 'string (string #\Esc) "[105;6u") nil)
    (,(concatenate 'string (string #\Esc) "[99999999u") nil)
    (,(concatenate 'string
                   (string #\Esc)
                   "[200~hello"
                   (string #\Esc)
                   "[201~x")
     (:collect-bracketed-paste t))))
