(in-package #:cl-tty-kit/test)

(defun test-prolog-unification ()
  (flet ((unified (left right)
           (let ((bindings (tty-prolog:unify left right)))
             (and (not (eq bindings tty-prolog:+fail+))
                  (tty-prolog:subst-bindings bindings left)))))
    (is-equal '(a b) (unified '(?x b) '(a ?y)))
    (is-equal '(a a) (unified '(?x ?x) '(a a)))
    (is-fail (tty-prolog:unify '(?x ?x) '(a b))
             "distinct constants cannot bind one variable twice")
    (is-fail (tty-prolog:unify '?x '(f ?x))
             "the occurs check rejects an infinite term")
    (let ((term (list 'loop)))
      (setf (rest term) term)
      (signals (error condition)
          (tty-prolog:unify term '(loop))
        (is (search "circular term" (princ-to-string condition)))))
    (signals (error condition)
        (tty-prolog:subst-bindings '((?x . ?y) (?y . ?x)) '?x)
      (is (search "circular variable chain" (princ-to-string condition))))))
