(in-package #:cl-tty-kit/test)

(defun %ansi-string (&rest parts)
  (with-output-to-string (out)
    (dolist (part parts)
      (write-string part out))))

(defun %single-cell-render-output (char style)
  (let ((screen (make-screen 1 1)))
    (screen-put-cell screen 0 0 char :style style)
    (render-screen screen)))

(defun %render-command-kinds (commands)
  (mapcar #'first commands))

(defparameter +render-style-cases+
  `((#\B (:bold) ,(ansi-bold) t)
    (#\I (:italic) ,(format nil "~C[3m" #\Esc) t)
    (#\U (:bold :underline) ,(format nil "~C[1;4m" #\Esc) t)
    (#\F ((:fg 196)) ,(format nil "~C[38;5;196m" #\Esc) t)
    (#\B ((:bg 17)) ,(format nil "~C[48;5;17m" #\Esc) t)
    (#\R ((:fg 1 2 3) (:bg 4 5 6))
     ,(format nil "~C[38;2;1;2;3;48;2;4;5;6m" #\Esc)
     t)
    (#\Z (:blink) nil nil)))

(defparameter +render-cursor-cases+
  `((,(make-cursor :x 3 :y 4)
     ,(%ansi-string (ansi-move-cursor 5 4)
                    (ansi-show-cursor)))
    (,(make-cursor :x 1 :y 2 :visible nil)
     ,(%ansi-string (ansi-move-cursor 3 2)
                    (ansi-hide-cursor)))))

(defun %assert-render-style-case (char style sgr expect-reset-p)
  (let ((output (%single-cell-render-output char style)))
    (if sgr
        (is (search sgr output)
            (format nil "style ~S should emit ANSI codes" style))
        (is (string= output
                     (%ansi-string (ansi-clear-screen)
                                   (ansi-move-cursor 1 1)
                                   (string char)))
            (format nil "unsupported style ~S should be ignored" style)))
    (when expect-reset-p
      (is (search (ansi-reset-style) output)
          (format nil "style ~S should reset ANSI state" style)))
    (is (search (string char) output))))

(defun %assert-render-cursor-case (cursor expected)
  (is (string= (render-cursor cursor) expected)))

(defun test-render-core ()
  (let ((screen (make-screen 2 2)))
    (screen-put-cell screen 0 0 #\H)
    (screen-put-cell screen 1 0 #\i)
    (screen-put-cell screen 0 1 #\!)
    (is (equal '(:string :cursor :cell :cell :newline :cell :cell)
               (%render-command-kinds
                (cl-tty-kit::%screen-render-commands screen)))))
  (let ((cursor (make-cursor :x 1 :y 2 :visible nil)))
    (is (equal '((:cursor 3 2) (:visibility nil))
               (cl-tty-kit::%cursor-render-commands cursor))))
  (do-test-case-bind (style-case +render-style-cases+
                                 (char style sgr expect-reset-p))
    (%assert-render-style-case char style sgr expect-reset-p))
  (is (null (cl-tty-kit::%style-sgr-codes 42)))
  (is (null (cl-tty-kit::%color-style-sgr-codes '(:foo 1))))
  (is (null (cl-tty-kit::%color-style-sgr-codes '(:fg 1 2))))
  (let ((screen (make-screen 2 1))
        (stream (make-string-output-stream)))
    (screen-put-cell screen 0 0 #\H)
    (screen-put-cell screen 1 0 #\i)
    (%assert-render-stream-output (stream (render-screen screen stream))
                                  (render-screen screen)))
  (let ((cursor (make-cursor :x 0 :y 0 :visible nil))
        (stream (make-string-output-stream)))
    (%assert-render-stream-output
     (stream (render-cursor cursor stream))
     (%ansi-string (ansi-move-cursor 1 1)
                   (ansi-hide-cursor))))
  (do-test-case-bind (cursor-case +render-cursor-cases+ (cursor expected))
    (%assert-render-cursor-case cursor expected))
  (let ((screen (make-screen 2 1))
        (cursor (make-cursor :x 1 :y 0)))
    (screen-put-cell screen 0 0 #\H)
    (screen-put-cell screen 1 0 #\i)
    (is (string= (render-frame screen cursor)
                 (%ansi-string (render-screen screen)
                               (ansi-move-cursor 1 2)
                               (ansi-show-cursor)))))
  (let ((screen (make-screen 2 1))
        (cursor (make-cursor :x 0 :y 0 :visible nil))
        (stream (make-string-output-stream)))
    (screen-put-cell screen 0 0 #\H)
    (screen-put-cell screen 1 0 #\i)
    (%assert-render-stream-output
     (stream (render-frame screen cursor stream))
     (%ansi-string (render-screen screen)
                   (ansi-move-cursor 1 1)
                   (ansi-hide-cursor))))
  t)
