(in-package #:cl-tty-kit)

(defun %write-diff-run (cells previous-cells start-index row-end stream)
  (declare (type simple-vector cells previous-cells)
           (type fixnum start-index row-end))
  (do ((index start-index (1+ index)))
      ((>= index row-end) row-end)
    (declare (type fixnum index))
    (let ((current (aref cells index))
          (old (aref previous-cells index)))
      (when (%cell-equal-p current old)
        (return index))
      (%write-cell current stream))))

(defun %diff-render-length (screen previous max-length)
  "Return the diff output length and whether it loses to a full repaint."
  (block too-long
    (let ((cells (screen-cells screen))
          (previous-cells (screen-cells previous))
          (width (screen-width screen))
          (height (screen-height screen))
          (length 0))
      (declare (type simple-vector cells previous-cells)
               (type fixnum max-length)
               (type fixnum width height length))
      (flet ((count-output (amount)
               (declare (type fixnum amount))
               (let ((next-length (+ length amount)))
                 (declare (type fixnum next-length))
                 (when (>= next-length max-length)
                   (return-from too-long (values next-length t)))
                 (setf length next-length))))
        (do ((y 0 (1+ y))
             (row-start 0 (+ row-start width)))
          ((>= y height) (values length nil))
          (declare (type fixnum y row-start))
          (let ((row-end (+ row-start width))
                (blank-suffix-start nil))
            (declare (type fixnum row-end)
                     (type (or null fixnum) blank-suffix-start))
            (do ((index row-start))
              ((>= index row-end))
              (declare (type fixnum index))
              (if (%cell-equal-p (aref cells index) (aref previous-cells index))
                  (incf index)
                  (let ((x (- index row-start)))
                    (declare (type fixnum x))
                    (when (and (null blank-suffix-start)
                               (%render-blank-cell-p (aref cells index)))
                      (setf blank-suffix-start
                            (%row-blank-suffix-start cells row-start width)))
                    (if (and blank-suffix-start (>= x blank-suffix-start))
                        (progn
                          (count-output (%diff-cursor-length x y))
                          (count-output 4)
                          (setf index row-end))
                        (progn
                          (count-output (%diff-cursor-length x y))
                          (do ()
                              ((or (>= index row-end)
                                   (%cell-equal-p
                                     (aref cells index)
                                     (aref previous-cells index))))
                            (count-output (%cell-rendered-length (aref cells index)))
                            (incf index)))))))))))))

(defun %write-diff (screen previous stream)
  "Write the sparse changes from PREVIOUS to SCREEN to STREAM."
  (let ((cells (screen-cells screen))
        (previous-cells (screen-cells previous))
        (width (screen-width screen))
        (height (screen-height screen))
        (wrote-output-p nil))
    (declare (type simple-vector cells previous-cells)
             (type fixnum width height)
             (type boolean wrote-output-p))
    (do ((y 0 (1+ y))
         (row-start 0 (+ row-start width)))
        ((>= y height) (values stream wrote-output-p))
      (declare (type fixnum y row-start))
      (let ((row-end (+ row-start width))
            (blank-suffix-start nil))
        (declare (type fixnum row-end)
                 (type (or null fixnum) blank-suffix-start))
        (do ((index row-start))
            ((>= index row-end))
          (declare (type fixnum index))
          (if (%cell-equal-p (aref cells index) (aref previous-cells index))
              (incf index)
              (let ((x (- index row-start)))
                (declare (type fixnum x))
                (when (and (null blank-suffix-start)
                           (%render-blank-cell-p (aref cells index)))
                  (setf blank-suffix-start
                        (%row-blank-suffix-start cells row-start width)))
                (%write-ansi-move-cursor (1+ y) (1+ x) stream)
                (setf wrote-output-p t)
                (if (and blank-suffix-start (>= x blank-suffix-start))
                    (progn
                      (%write-ansi-clear-line stream)
                      (setf index row-end))
                    (setf index
                          (%write-diff-run cells previous-cells index row-end stream))))))))))

(defun %screen-render-length (screen)
  (let* ((cells (screen-cells screen))
         (length 10)
         (height (screen-height screen))
         (limit (length cells)))
    (declare (type simple-vector cells)
             (type fixnum length height limit))
    (do ((index 0 (1+ index)))
        ((>= index limit)
         (unless (zerop height)
           (incf length (1- height)))
         length)
      (declare (type fixnum index))
      (incf length (%cell-rendered-length (aref cells index))))))

(defun %screen-render-length-exceeds-p (screen maximum)
  "Return whether a complete repaint of SCREEN is longer than MAXIMUM."
  (let* ((cells (screen-cells screen))
         (length 10)
         (height (screen-height screen))
         (limit (length cells)))
    (declare (type simple-vector cells)
             (type fixnum length height maximum limit))
    (when (> length maximum)
      (return-from %screen-render-length-exceeds-p t))
    (do ((index 0 (1+ index)))
        ((>= index limit)
         (or (zerop height)
             (> (+ length (1- height)) maximum)))
      (declare (type fixnum index))
      (incf length (%cell-rendered-length (aref cells index)))
      (when (> length maximum)
        (return-from %screen-render-length-exceeds-p t)))))

(defun %minimum-screen-render-length (screen)
  "Return a lower bound for a complete repaint of SCREEN."
  (+ 10
     (length (screen-cells screen))
     (let ((height (screen-height screen)))
       (declare (type fixnum height))
       (if (zerop height) 0 (1- height)))))

(defun %write-diff-plan (screen plan stream)
  (let ((cells (screen-cells screen))
        (width (screen-width screen))
        (operations (diff-plan-operations plan)))
    (declare (type simple-vector cells)
             (type (vector fixnum) operations)
             (type fixnum width))
    (do ((operation-index 0 (+ operation-index 2))
         (operation-limit (fill-pointer operations)))
        ((>= operation-index operation-limit)
         (values stream (plusp operation-limit)))
      (declare (type fixnum operation-index operation-limit))
      (let ((start (aref operations operation-index))
            (end (aref operations (1+ operation-index))))
        (declare (type fixnum start end))
        (multiple-value-bind (y x) (truncate start width)
          (declare (type fixnum y x))
          (%write-ansi-move-cursor (1+ y) (1+ x) stream)
          (if (minusp end)
              (%write-ansi-clear-line stream)
              (do ((index start (1+ index)))
                  ((>= index end))
                (declare (type fixnum index))
                (%write-cell (aref cells index) stream))))))))

(defun %write-preferred-diff (screen previous stream &optional plan changed-since)
  "Write the smaller valid screen update and report its rendering strategy."
  (if (not (%same-screen-dimensions-p screen previous))
      (values (%write-screen screen stream) t t)
      (if plan
          (let ((diff-length (%plan-diff-length screen previous plan changed-since)))
            (if (or (< diff-length (%minimum-screen-render-length screen))
                    (%screen-render-length-exceeds-p screen diff-length))
                (multiple-value-bind (result wrote-output-p)
                    (%write-diff-plan screen plan stream)
                  (values result wrote-output-p nil))
                (values (%write-screen screen stream) t t)))
          (multiple-value-bind (diff-length too-long-p)
              (%diff-render-length screen previous most-positive-fixnum)
            (declare (ignore too-long-p))
            (if (or (< diff-length (%minimum-screen-render-length screen))
                    (%screen-render-length-exceeds-p screen diff-length))
                (multiple-value-bind (result wrote-output-p)
                    (%write-diff screen previous stream)
                  (values result wrote-output-p nil))
                (values (%write-screen screen stream) t t))))))
(defun %render-diff-output (screen previous stream &optional plan changed-since)
  (%with-style-sgr-sequence-cache
    (if stream
        (multiple-value-bind (result diff-output-p full-repaint-p)
            (%write-preferred-diff screen previous stream plan changed-since)
          (declare (ignore result))
          (values stream diff-output-p full-repaint-p))
        (let ((output (make-string-output-stream)))
          (multiple-value-bind (result diff-output-p full-repaint-p)
              (%write-preferred-diff screen previous output plan changed-since)
            (declare (ignore result))
            (values
              (get-output-stream-string output)
              diff-output-p
              full-repaint-p))))))



(defun %render-frame-diff-output (screen previous cursor previous-cursor stream &optional plan changed-since) (%with-style-sgr-sequence-cache (if stream (%write-frame-diff screen previous cursor previous-cursor stream plan changed-since) (let ((output (make-string-output-stream))) (multiple-value-bind (result diff-output-p full-repaint-p) (%write-frame-diff screen previous cursor previous-cursor output plan changed-since) (declare (ignore result)) (values (get-output-stream-string output) diff-output-p full-repaint-p))))))

(defun %write-frame-diff (screen previous cursor previous-cursor stream &optional plan changed-since) (multiple-value-bind (result diff-output-p full-repaint-p) (%write-preferred-diff screen previous stream plan changed-since) (declare (ignore result)) (if (or diff-output-p (null previous-cursor) (not (%cursor-equal-p cursor previous-cursor))) (values (%write-cursor cursor stream) t full-repaint-p) (values stream nil full-repaint-p))))
